exports.glossary = [{
  "categoryEN": "textile",
  "categoryCN": "面料",
  "words": [["2-ply", "双合股"], ["Acetate", "醋酸纤维/醋酯纤维"], ["Acrylic", "人造毛/亚克力沙"], ["Alpaca", "羊驼毛"], ["Angora hair", "兔毛"], ["Argyle", "钻石纹"], ["Bamberg", "宾霸里布"], ["Bamboo", "竹纤维"], ["Barathea", "巴拉西厄绸"], ["Birdseye", "鸟眼"], ["Blend", "混织"], ["Cable knit", "绞花毛衣"], ["Camel hair", "驼毛"], ["Canvas (Fabric)", "帆布 （面料）"], ["Canvas (Tailoring)", "麻衬 （西服）"], ["Carbon fiber", "碳纤维"], ["Carpincho", "水豚皮"], ["Cashmere", "羊绒"], ["Cavalry", "骑兵队/双斜纹布"], ["Chalk strip", "粉笔纹"], ["Chambray", "青年布"], ["Cheviot tweed", "切维厄特花呢/雪福特花呢"], ["Corduroy", "灯芯绒"], ["Corozo", "果实扣"], ["Cotton", "棉"], ["Cotton flannel", "棉绒"], ["Covert", "猎纹"], ["Diamond quilting", "菱格绗缝"], ["Donegal tweed", "多尼戈尔花呢"], ["Doppioni silk", "双宫丝"], ["Duffle wool", "比利时粗呢/道尔夫粗呢"], ["Estate Tweed", "庄园花呢"], ["Fearnought", "粗绒呢"], ["Fil d' Ecosse", "莱尔棉线"], ["Filament", "长纤/丝"], ["Fine gauge", "细针"], ["Flannel", "法兰绒"], ["Fringe", "边穗"], ["Fully fashioned", "成型编制"], ["Gabardine", "扎别丁/华达呢/斜纹布"], ["Glen check/POW (Prince of Wales) check", "格兰纹/亲王格"], ["Goat skin", "山羊皮"], ["Gore-tex", "戈尔斯特面料"], ["Grenadine", "针织纱网"], ["Gros grain", "罗缎"], ["Gun club", "俱乐部格"], ["Harris tweed", "哈里斯花呢"], ["Hemp", "粗麻纤维"], ["Herringbone", "鱼骨纹"], ["High-twist", "高捻度"], ["Hogskin", "猪皮"], ["Hopsack", "席纹呢"], ["Horn button", "牛角扣"], ["Hounds tooth", "犬牙混织"], ["Jacquard", "提花布"], ["Khaki drill", "卡其布"], ["Lambswool", "羊羔毛"], ["Linen", "亚麻"], ["London shrunk", "伦敦布"], ["LY=Lycra", "莱卡/杜邦弹性纱"], ["Lyocell", "莱赛尔/天丝"], ["Madder", "茜草染"], ["Mélange", "混色"], ["Merino wool", "美利奴羊毛"], ["Metallic yarn", "金属纱"], ["Micro fiber", "超细纤维"], ["Modal", "莫代尔纤维"], ["Mohair", "马海毛"], ["Mohair", "马海毛"], ["Mother of pearl button", "珍珠母扣"], ["Nailhead", "钉头布"], ["Nylon/Polyamide", "尼龙/棉纶"], ["OP=Spandex", "弹性纤维/氨纶"], ["Oxford colthing", "牛津布"], ["P/C=Polyester/Cotton", "聚酯纤维/棉"], ["PA=Polyamide", "棉纶/聚醯胺纤维"], ["PC=Acrylic", "腈纶/亚克力"], ["Peccary", "西貒皮"], ["Pin stripe", "细条纹"], ["Pinhead", "针头布"], ["Ply", "股（量词）"], ["Polka-dot", "波点"], ["Polyester", "聚酯纤维/涤纶"], ["Raffia", "酒椰纤维"], ["Rayon", "人造棉/人造丝"], ["Recycled fibers", "环保纤维"], ["Regimental", "军团斜条纹领带"], ["Russel Plaid", "拉塞尔格"], ["Satin", "平缎"], ["Sea island cotton", "海岛棉"], ["Seersucker", "泡泡纱/沙喀尔棉"], ["Serge", "塞结/哔叽/45度角斜纹布"], ["Shadow strip", "暗纹"], ["Shantung silk", "山东丝/山东绸"], ["Sharkskin", "鲨鱼皮纹"], ["Sheepskin", "羊皮"], ["Shetland tweed", "设得兰花呢"], ["Shetland wool", "设得兰羊毛"], ["Silk", "蚕丝"], ["Spun", "短纤"], ["Tactel", "特达/杜邦弹性纱"], ["Tartan", "族氏格"], ["Tartan", "格纹花呢"], ["Tencel", "天丝棉"], ["Terry cloth", "毛圈棉"], ["Tussah silk", "柞蚕丝"], ["Tweed", "粗花呢"], ["Vegetable tanned ", "植鞣"], ["Viscose", "人造丝/粘胶纤维"], ["Voile", "巴厘纱"], ["Wax cotton", "油蜡布"], ["Whipcord", "斜纹马裤呢"], ["Window/Pane check", "窗格"], ["Wool", "羊毛"], ["Woollen", "粗纺"], ["Worsted", "精纺"], ["Yak hair", "牦牛毛"]]
}, {
  "categoryEN": "RTW",
  "categoryCN": "成衣",
  "words": [[" Sports", "运动"], ["Anorak", "带风帽的夹克/滑雪衫"], ["Balmaccan coat", "短款单排扣风衣/巴尔马肯风衣"], ["Banded", "立领"], ["Beachwear", "沙滩服"], ["Bespoke ", "定制"], ["Blouson", "休闲夹克"], ["Boxer", "四角内裤"], ["Breek", "猎装短裤"], ["Brief", "贴身三角内裤"], ["Button down", "双扣领"], ["Cable knit", "绞花毛衣"], ["Camouflage", "迷彩图案"], ["Cape", "斗篷"], ["Cardigan", "开襟毛衣"], ["Chesterfield coat", "切斯特菲尔德单排扣大衣"], ["Classic", "经典"], ["Club collar", "圆角领"], ["Contemporary", "当代"], ["Country ", "郊野"], ["Country clothing", "郊野服饰"], ["Cover coat", "猎纹大衣"], ["Crew neck", "圆领"], ["Cricket sweater", "板球毛衣"], ["Crombie coat", "克伦比大衣"], ["Cutaway (Shirt)", "一字领"], ["Denim", "丹宁布"], ["Designer", "设计师"], ["Dressing gown", "晨衣"], ["Duffle coat", "粗呢大衣/渔夫大衣/道尔夫大衣"], ["Dust coat", "防尘大衣"], ["Fair isle sweater", "费尔岛毛衣"], ["Field jacket", "野战外套"], ["Fly placket", "暗门襟"], ["Forward-point", "前角领"], ["Ghillie collar", "吉利领"], ["Great coat", "军大衣"], ["Guard's coat", "警卫大衣"], ["Hacking jacket", "骑装夹克"], ["Harrington jacket", "哈灵顿夹克"], ["Jumper", "套衫"], ["Knitwear", "针织衫"], ["Leatherwear", "皮衣"], ["Loden coat", "洛登大衣"], ["Lounge trousers", "居家裤"], ["Loungewear", "家居便服"], ["Mackintosh/Mac", "防雨风衣"], ["Militaria", "军装/军品"], ["Minimalism", "极简主义"], ["Norfolk jacket", "诺福克猎装夹克"], ["Outdoors", "户外"], ["Outwear", "外套"], ["Parka", "抗寒外套"], ["Patchwork", "相拼缝合"], ["Pea coat", "双排扣短大衣"], ["Placket", "门襟"], ["Polo coat", "马球大衣"], ["Pyjama", "睡衣"], ["Quilted jacket", "绗缝外套"], ["Raglan sleeve", "插肩/拉格伦"], ["Raw denim", "原浆"], ["Reefer coat", "双排扣海军外套"], ["Resort wear", "度假装"], ["Retro", "复古"], ["Roll neck", "高领"], ["Saddle shoulder", "马鞍膊"], ["Safari jacket", "游猎夹克"], ["Seasonal collection", "当季成衣"], ["Selvedge", "赤耳"], ["Set-in sleeve", "装袖/接袖"], ["Shetland turtleneck sweater", "高领设得兰粗花呢毛衣"], ["Shooting vest", "猎装马甲"], ["Smock", "罩衫/工装外套"], ["Snap-tab", "有襻领"], ["Sportswear", "运动服"], ["Spread collar", "展开领"], ["Storm collar", "防风领"], ["Street", "街头"], ["Swim short", "游泳短裤"], ["Swimwear", "泳装/泳衣"], ["Track pants", "运动裤"], ["Trench coat", "战壕大衣"], ["Trunk", "贴身四角内裤"], ["Ulster coat", "伍斯特大衣"], ["Underwear", "内衣"], ["V neck", "V领"], ["Work wear", "工装"]]
}, {
  "categoryEN": "Tailoring",
  "categoryCN": "西服",
  "words": [["Action back", "延展背"], ["Affected", "刻意"], ["Arm hole/Arm scye", "袖洞"], ["Artisan", "艺匠"], ["Bar tack", "加固线迹"], ["Bellows pocket", "风箱式口袋"], ["Bespoke ", "专属定制"], ["Black tie", "黑领结（小礼服简称）"], ["Blazer", "布雷泽夹克"], ["Bowtie", "领结"], ["Box pleat", "中褶/箱型褶裥"], ["British warm", "不列颠暖呢"], ["Button hole", "扣眼"], ["Button stance", "扣位"], ["Casual", "休闲的"], ["Chic", "时髦"], ["Classic", "经典"], ["Clean", "利落"], ["Cobbler", "修鞋匠"], ["Collar", "领子"], ["Cordwainer", "制鞋师"], ["Cotton drill", "单面绒棉布"], ["Cotton wadding", "棉条"], ["Craftsman", "工匠"], ["Cuff", "袖口"], ["Cummerbund", "腰封"], ["Cutaway(Outwear)", "开摆（指晨礼服外套)"], ["Cutter", "制版师"], ["Cutting", "剪裁"], ["Dart", "省道/褶"], ["Dinner Jacket", "小晚礼服/无尾晚礼服"], ["Distressed", "松弛"], ["Down", "羽绒"], ["Drape", "挺坠"], ["Dressed-down", "便装"], ["Dressed-up", "盛装"], ["Easy", "惬意"], ["Elegance", "优雅"], ["Epaulette", "肩章"], ["Finishing", "后续修整"], ["Fitting", "试身"], ["Flap", "袋盖"], ["Fly front", "掩襟"], ["Formal", "端庄的"], ["Forward pleat", "前褶"], ["Full belt", "全腰带"], ["Guesset", "角撑"], ["Haberdasher", "男士服饰店"], ["Hacking pocket", "斜袋"], ["Half belt", "后腰带"], ["Hand made", "手制"], ["Hand stitch", "手缝"], ["Hatter", "制帽师"], ["Hem", "翻边"], ["Inverted pleat", "暗裥"], ["Ironing", "熨烫"], ["Jacket", "西服夹克"], ["Jetted pocket/Besom pocket", "唇袋"], ["Lapel", "翻领/驳领"], ["Lapped seam", "搭边"], ["Made to measure", "选版定制"], ["Made to order", "选款定制"], ["Madras", "马德拉斯棉布/格纹棉布"], ["Masculine", "阳刚"], ["Melton", "麦尔顿呢"], ["Moleskin", "绒面厚棉布"], ["Morning coat", "晨礼服"], ["Nonchalant", "不经意"], ["Notch lapel", "平驳领"], ["Open shoulder", "平肩"], ["Pad stitch", "纳针/扳针法"], ["Patch pocket", "贴袋"], ["Peak lapel", "枪驳领"], ["Pleated", "褶"], ["Raglan shoulder", "斜肩"], ["Ready to wear (RTW)", "成衣"], ["Reverse pleat", "反褶"], ["Roped shoulder", "翘肩"], ["Seamstress", "女缝纫师"], ["Sewing", "缝制"], ["Shawl lapel", "圆领"], ["Shearling", "皮毛一体"], ["Shirt", "衬衫"], ["Shoemaker", "鞋匠"], ["Side pleat", "两侧褶裥"], ["Skirt", "西服下摆"], ["Smart", "精神"], ["Sporty", "运动的"], ["Sprezzatura", "潇洒"], ["Suit", "西服套装"], ["Swelled edge", "双珠针边"], ["Tail", "大晚礼服/燕尾服"], ["Tailor", "裁缝"], ["Tailored", "裁气"], ["Tailoring", "西服"], ["Ticket pocket", "票袋"], ["Tie", "领带"], ["Trousers", "西裤"], ["Vent", "后衩"], ["Vintage", "温古"], ["Vulcanize", "硫化/硬化"], ["Waistcoat", "马甲"], ["Welted pocket", "嵌线袋"], ["White tie", "白领结（大礼服简称）"]]
}, {
  "categoryEN": "Footwear",
  "categoryCN": "鞋履",
  "words": [["Apron stitich", "围缝线"], ["Arch", "足弓"], ["Bevelled waist", "舷底"], ["Black", "布莱克底"], ["Boar's bristle", "猪鬃毛"], ["Box calf", "光面皮革"], ["Bridle Leather", "马勒皮"], ["Buck", "白鹿皮"], ["Calf", "牛皮"], ["Cap toe", "结头鞋"], ["Chisel toe", "小方头"], ["Clicking", "切革"], ["Closing", "缝合"], ["Cordovan", "马臀皮"], ["Cuban heel", "古巴跟"], ["Dainite sole", "戴氏胶底"], ["Derby", "德比鞋"], ["Elastic side", "侧松紧"], ["Espadrille", "麻绳底鞋"], ["Fiddle back", "琴底"], ["Fitting", "试脚"], ["Ghillie shoe", " 苏格兰吉利鞋"], ["Good year", "固特异"], ["Hand sewn", "手缝底"], ["Hatched grain", "斜线轧纹革"], ["Imitation Brogue", "仿布洛克"], ["In-sole", "鞋垫"], ["Lasting", "定型"], ["Loafer", "乐福鞋"], ["Medallion", "雕花"], ["Moccasin", "莫卡辛鞋"], ["Museum calf", "古董皮"], ["Natural grain", "自然纹革"], ["Norvegese stitching", "挪威缝"], ["Nubuck", "正绒面革"], ["Oxford", "牛津鞋"], ["Patent leather", "漆皮"], ["Patina", "旧色（年久而产生的光泽）"], ["Pebble grain", "卵石轧纹革"], ["Penny loafer", "便士乐福鞋"], ["Penny strap", "便士鞋"], ["Polish", "擦光"], ["Pump", "礼服鞋"], ["Round toe", "圆头"], ["Russian Reindeer", "驯鹿皮"], ["Saddle Leather", "马鞍皮"], ["Scotch grain", "苏格兰纹"], ["Shoe horn", "鞋拔"], ["Shoe tree", "鞋撑"], ["Shrunk calf", "缩水皮"], ["Slipper", "居家便鞋"], ["Sock", "内衬"], ["Soft-square toe", "圆方头"], ["Spectator", "观众鞋"], ["Split toe", "中分头"], ["Square toe", "方头"], ["Storm welt", "防水边条"], ["Strap/Monk", "僧侣鞋"], ["Suede", "翻绒面革"], ["Swan neck", "鹄颈纹"], ["Swatch", "皮料本"], ["Tassel loafer", "吊穗乐福鞋"], ["Tassels", "吊穗，流苏"], ["Toe tip", "铁片"], ["Trainer", "（英）运动鞋"], ["Unlined", "无结构"], ["Vamp", "鞋面"], ["Vibram sole", "阀氏胶底"], ["Welt", "边条"], ["Wing tip", "翼梢"]]
}, {
  "categoryEN": "Leather Goods",
  "categoryCN": "皮具",
  "words": [["Attaché case", "外交官公文包"], ["Brief case", "公文包"], ["Cartridge bag", "弹药包"], ["Clutch", "手拿包"], ["Duffle bag", "行李包"], ["Gun slip", "枪带"], ["Holdall/Travel bag", "旅行包"], ["Medical bag", "医药包"], ["Messenger bag", "邮差包"], ["Music bag", "乐谱包"], ["Rucksack", "背包"], ["Satchel bag", "挎包/斜肩包"], ["Shoulder bag", "肩包"], ["Tote bag", "托特包/开口手提包"], ["Weekender", "周末包"]]
}, {
  "categoryEN": "Accessories",
  "categoryCN": "配饰",
  "words": [["Ascot", "领巾/阿斯科特式领带"], ["Beanie", "线帽"], ["Belt", "腰带"], ["Beret", "贝雷帽"], ["Blanket", "毛毯"], ["Boater", "水手帽"], ["Bracelet", "手链"], ["Braces", "背带"], ["Brim", "帽檐"], ["Buckle", "扣"], ["Coke/Bowler", "圆顶硬礼帽"], ["Collar bar", "领带撑"], ["Collar stay", "领撑"], ["Crest", "刺绣勋章"], ["Cuff knots", "袖结"], ["Cufflinks", "袖扣"], ["Eyewear", "眼镜"], ["Fedora ", "费多拉软毡帽"], ["Felt hat", "填充帽"], ["Flat cap", "平顶帽"], ["Fur hat", "毛皮帽"], ["Furnishing accessories", "生活用品"], ["Gloves", "手套"], ["Hankderchief", "手帕"], ["Jewellery", "首饰"], ["Knit tie", "针织领带"], ["Lapel pin", "领针"], ["Newsboy cap/Bakerboy cap", "报童帽"], ["Panama", "巴拿马帽"], ["Pin badge", "领章"], ["Pocket square", "口袋巾"], ["Pork pie", "派型软毡帽"], ["Self-tipped", "同面领带"], ["Skipper cap", "船长帽"], ["Socks", "袜"], ["Solid umbrella", "整木中骨"], ["Stick umbrella", "拼木中骨"], ["Throw", "披肩"], ["Tie", "领带"], ["Tie slide/Tie clip/Tie bar", "领带夹"], ["Tipped tie", "双面领带"], ["Top hat", "高顶礼帽"], ["Trilby", "软毡帽"], ["Tube umbrella", "金属中骨"], ["Umbrella", "雨伞"], ["Untipped tie", "单面领带"], ["Walking stick", "拐杖"]]
}, {
  "categoryEN": "Business",
  "categoryCN": "商务",
  "words": [["Bunch", "料本"], ["Buying office", "采购办事处"], ["Ex-works", "工厂交货价/出厂价"], ["FOB (Free on Board)", "出厂价格"], ["Line sheet", "产品目录"], ["Manikin", "人形模特"], ["Pattern", "制衣样板"], ["Pro-forma", "估价单"], ["SMV (Standard Minute Value)", "标准分钟价值（服装缝纫部门）"], ["Style number", "样式代号"], ["Swatch card", "色卡"], ["Time and action calender", "行动计划"], ["Up-charge/Sur-charge", "操作加价"], ["VAT", "增值税"], ["Vender", "厂商/供货商"]]
}, {
  "categoryEN": "Others",
  "categoryCN": "其他",
  "words": [["Barber", "理发（店）"], ["Classic (consumer type)", "品位男士"], ["Contemporary (consumer type)", "摩登男士"], ["Designer (consumer type)", "风尚男士"], ["Fragrance", "香氛"], ["Furnishing ", "私人用品"], ["Grooming", "理容"], ["Outdoors (consumer type)", "户外运动爱好者"], ["Personal care", "个人护理"], ["Stationary", "文具"], ["Street (consumer type)", "潮流达人"], ["Valet", "落地衣架"]]
}];
